-- SCRIPT E TABELA CRIANDO NA SCHEMA VEMSER_WILLIAN;

-- CRIANDO A TABELA ESTUDANTE;
CREATE TABLE ESTUDANTE (
id NUMBER NOT NULL,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) UNIQUE NOT NULL,
ativo CHAR(1) NOT NULL,
PRIMARY KEY (id)
);

-- ADICIONANDO UMA SEQUÊNCIA PARA ESTUDANTE;
CREATE SEQUENCE seq_estudante
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

-- INSERINDO REGISTROS NA TABELA;

-- 1
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Marcos', TO_DATE('19-01-1992', 'dd-mm-yyyy'), 1231452100, 'S');

-- 2
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Maria', TO_DATE('11-02-2000', 'dd-mm-yyyy'), 1224133199, 'S');

-- 3
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Carlos', TO_DATE('09-08-2000', 'dd-mm-yyyy'), 1235899779, 'S');

-- 4
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Pedro', TO_DATE('05-03-1998', 'dd-mm-yyyy'), 1231415521, 'S');

-- 5
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Yuri', TO_DATE('31-07-1999', 'dd-mm-yyyy'), 1231551562, 'S');

-- 6
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Willian', TO_DATE('20-08-1997', 'dd-mm-yyyy'), 1112213155, 'S');

-- 7
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Gabriel', TO_DATE('21-09-1992', 'dd-mm-yyyy'), 1235563222, 'S');

-- 8
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'José', TO_DATE('25-10-1998', 'dd-mm-yyyy'), 5555222133, 'S');

-- 9
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Moises', TO_DATE('13-02-1991', 'dd-mm-yyyy'), 5632121123, 'S');

-- 10
INSERT INTO ESTUDANTE (ID, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO) VALUES (seq_estudante.nextval, 'Guilherme', TO_DATE('12-03-1999', 'dd-mm-yyyy'), 1998220352, 'S');

-- SELECIONANDO TODOS OS REGISTROS A PARTIR DA TABELA ESTUDANTE;
SELECT * FROM ESTUDANTE